# Docker for OSX uses a VM so we need 0.0.0.0 instead of 127.0.0.1
host: 0.0.0.0

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kaushik Gopal's Blog
author:
  name: "Kaushik Gopal"
  twitter: kaushikgopal
  bio-url: "https://jkl.gg"

external-url-indicator: " »"

# Link settings
root: /
permalink: /:title/

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8

# front matter defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # pages, posts, drafts are valid
    values:
      layout: "post"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - docker-compose-publish.yml
  - docker-compose.yml
  - firebase.json
  - .idea/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
